version: '3.4'

services:
  bugtracker:
    image: ${DOCKER_REGISTRY-}bugtracker
    build:
      context: .
      dockerfile: BugTracker/Dockerfile
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      SA_PASSWORD: "Testing123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
